language: node_js
node_js:
  - "5.0"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.10"

script:
  - npm test

after_success:
  cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
